depth:
  mlp:
    n_hidden_layers: 2
    n_inputs: 36
    downsample: 2         # downsample the image size to get the output depths - note new_len = new_len // 2 ** downsample
    n_hidden_nodes: 256
    activation: 'ReLU'

vit:
  model_dim: 36
  embed:
    img_size: [1024, 768]  # image size for DIODE data
    patch_size: 16
    in_channels: 3
  transformer:
    n_heads: 4
    n_channels: 12
    tfm_depth: 5
    
  mlp:
    n_hidden_layers: 2
    n_hidden_nodes: 128
    activation: 'GELU'

train:
  n_epochs: 5
  batch_size: 8
  lr: 0.001
